import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}


// "use client";
// import { useEffect, useState } from 'react';

// export default function Layout({ children }) {
//   const [loading, setLoading] = useState(true);
//   const [cookieAccepted, setCookieAccepted] = useState(false);

//   useEffect(() => {
//     setTimeout(() => setLoading(false), 3000);
//   }, []);

//   return (
//     <>
//       {loading ? (
//         <div className="splash-screen">
//           <h1>Loading...</h1>
//         </div>
//       ) : (
//         <>
//           {!cookieAccepted && (
//             <div className="cookie-popup">
//               <p>We use cookies for better experience.</p>
//               <button onClick={() => setCookieAccepted(true)}>Accept</button>
//             </div>
//           )}
//           {children}
//         </>
//       )}
//     </>
//   );
// }
